MJU-TeamProject2/MJU-BE

.github/workflows/deploy.yml

feat: Add CI/CD yml File

---

.github/workflows/deploy.yml

feat: Input Data about AWS Services

---

.github/workflows/deploy.yml

feat: Fix Deploy.yml to Upload EC2

---

.github/workflows/deploy.yml

release: 0.1.13

---

.github/workflows/deploy.yml

feat: fix deploy yml

---

.github/workflows/deploy.yml

feat: fix deploy yml (#17)

---

.github/workflows/deploy.yml
src/main/resources/application.yml

feat: Create Pipeline

---

.github/workflows/deploy.yml
src/main/resources/application.yml

release: 0.1.14

---

.gitignore
src/test/resources/application.yml

hot-fix: Add CI/CI Setting in Test Package

---

src/main/resources/application.yml
src/test/resources/application.yml

release: 0.1.15 

---

.github/workflows/deploy.yml

release: 0.1.161

---

src/main/resources/application.yml
src/test/resources/application.yml

release: 0.1.162

---

src/main/resources/application.yml
src/test/resources/application.yml

release: 0.1.17

---

src/main/resources/application.yml
src/test/resources/application.yml

release: 0.1.171

---

.github/workflows/deploy.yml
build.gradle

hot-fix: Fix the build file name (#40)

---

.github/workflows/deploy.yml

hot-fix: build 파일 업로드를 위한 절대 경로 사용 (#42)

---

.github/workflows/deploy.yml

hot-fix: Debugging Pipeline Function (#44)

---

.github/workflows/deploy.yml

hot-fix: Use Absolute Path to get Build File (#46)

---

.github/workflows/deploy.yml

hot-fix: add delay before copy to ec2 (#48)

---

.github/workflows/deploy.yml

hot-fix: change build file permission (#52)

---

.github/workflows/deploy.yml

hot-fix: use Absolute Path (#54)

---

.github/workflows/deploy.yml

* hot-fix: add uploading artifact code
* 
*
*
*

hot-fix: add uploading artifact code (#56)

---

.github/workflows/deploy.yml

* hot-fix: add uploading artifact code
* hot-fix: use v3 to upload and download artifact
* 
*
*
*

hot-fix: Use v3 to upload and download artifact (#58)

---

.github/workflows/deploy.yml

* hot-fix: add uploading artifact code
* hot-fix: use v3 to upload and download artifact
* hot-fix: …

hot-fix: Use Relative Path (#60)

---

src/main/java/com/example/demo/common/dto/ErrorResponse.java
src/main/java/com/example/demo/common/exception/CommonErrorCode.java
src/main/java/com/example/demo/common/exception/CustomException.java
src/main/java/com/example/demo/common/exception/GlobalExceptionHandler.java

* exception handler를 통해 에러 발생 시에도 응답 형식을 유지합니다.
*exception handler가 추가되었습니다.
*없습니다.
*없습니다.

feat: GlobalExceptionHandler 수정

---

src/main/java/com/example/demo/common/util/CorsConfig.java
src/main/java/com/example/demo/common/util/SecurityConfig.java

Build: cors setting

---

src/main/java/com/example/demo/common/util/CorsConfig.java

hotfix:Update CorsConfig.java

---

.github/workflows/deploy.yml
src/main/java/com/example/demo/common/dto/ErrorResponse.java
src/main/java/com/example/demo/common/exception/CommonErrorCode.java
src/main/java/com/example/demo/common/exception/CustomException.java
src/main/java/com/example/demo/common/exception/GlobalExceptionHandler.java
src/main/java/com/example/demo/common/util/CorsConfig.java
src/main/java/com/example/demo/common/util/SecurityConfig.java

release: 0.1.173

---

.github/workflows/qodana_code_quality.yml
src/main/java/com/example/demo/common/util/CorsConfig.java

* cors 에러 수정 및 정적 분석 속도 향상
* cors config의 setAllowedCredentials(true -> false)
qodana.yml의 pr-mode: false -> true
*
*

build: cors 에러 수정 및 qodana 분석 속도 향상

---

src/main/java/com/example/demo/common/util/CorsConfig.java

* cors 에러 수정 및 qodana 속도 향상
* cors config & qodana.yml 파일 수정
*
*

build: cors 에러 수정 및 qodana 속도 향상

---

src/main/java/com/example/demo/clothes/entity/ClothesCategory.java
src/main/java/com/example/demo/clothes/repository/ClothesRepository.java
src/main/java/com/example/demo/clothes/service/ClothesService.java
src/main/java/com/example/demo/clothes/util/StringToClothesCategoryConverter.java
src/main/java/com/example/demo/common/util/WebConfig.java
src/main/java/com/example/demo/controller/ClothesController.java
src/main/java/com/example/demo/controller/ClothesControllerImpl.java

* 카테고리에 맞는 의상을 조회한다.
* ClothesCategory라는 Enum 타입을 통해 의상을 조회하는 API를 추가한다.
* Enum 타입을 @PathVariable 어노테이션으로 받아야 하는 경우를 대비해 Converter Class를 추가했다.
* 각 Enum에 대한 Converter를 추가하는 것 이외에 @PathVariable 어노테이션으로 Enum 타입을 받을 수 있는 방법이 있으면 공유 부탁드립니다!

feat: 카테고리별 의상 조회

---

.gitignore
docker-compose-local.yml
src/main/java/com/example/demo/cart/dto/request/AddToCartItemRequest.java
src/main/java/com/example/demo/cart/dto/request/UpdateCartItemRequest.java
src/main/java/com/example/demo/cart/dto/response/GetCartResponse.java
src/main/java/com/example/demo/cart/entity/Cart.java
src/main/java/com/example/demo/cart/repository/CartRepository.java
src/main/java/com/example/demo/cart/service/CartService.java
src/main/java/com/example/demo/clothes/service/ClothesService.java
src/main/java/com/example/demo/common/security/AccessPath.java
src/main/java/com/example/demo/controller/CartController.java
src/main/java/com/example/demo/controller/CartControllerImpl.java
src/main/java/com/example/demo/customer/service/CustomerService.java
src/main/java/com/example/demo/exception/CartErrorCode.java
src/main/java/com/example/demo/exception/CartNotFoundException.java

* 장바구니 기능을 추가하여 고객이 장바구니에 상품을 조회, 추가, 수정, 삭제할 수 있도록 지원하는 기능을 구현합니다.
* 장바구니 Controller Interface 작성
* 장바구니 조회, 추가, 수정, 삭제를 위한 DTO 구현
* 장바구니 엔티티 추가 (Customer, Clothes와 수량 정보 포함)
* JpaRepository 인터페이스 구현
* CartController 및 비즈니스 로직 구현
* .gitignore 파일에 `mysql_data` 경로 추가
* Compose-local 세팅 파일 추가
* 의존성을 낮추기 위한 `findById` 메서드 생성
* 장바구니 상품 조회, 추가, 수정, 삭제 기능이 정상적으로 작동하는지 확인
* 상품을 찾지 못할 때 발생하는 에러 코드가 올바르게 반환되는지 검증

feat: 장바구니 기능 구현

---

src/main/java/com/example/demo/clothes/dto/request/UpdateClothesRequest.java
src/main/java/com/example/demo/clothes/entity/Clothes.java
src/main/java/com/example/demo/clothes/entity/ClothesSize.java
src/main/java/com/example/demo/clothes/repository/ClothesRepository.java
src/main/java/com/example/demo/clothes/repository/ClothesSizeRepository.java
src/main/java/com/example/demo/clothes/service/ClothesService.java
src/main/java/com/example/demo/common/security/AccessPath.java
src/main/java/com/example/demo/controller/ClothesController.java
src/main/java/com/example/demo/controller/ClothesControllerImpl.java
src/main/java/com/example/demo/exception/ClothesErrorCode.java
src/main/java/com/example/demo/exception/ClothesSizeNotFoundException.java

* 의류 정보를 수정 및 삭제할 수 있는 api가 추가되었습니다.
* ClothesController 인터페이스 추가 및 상품 수정/삭제 API 구현하였습니다.
* UpdateClothesRequest DTO가 추가되었습니다.(전부 NOT_REQUIRED로 설정하였습니다)
* Clothes에 상품 수정 및 삭제 메소드가 추가되었습니다.
* 삭제된 상품을 제외한 상품 조회로 로직을 수정하였습니다.(ClothesRepository 수정)
* ClothesSizeRepository 및 ClothesSizeNotFoundException을 생성하였습니다.
* 수정 및 삭제 API 호출 시 의도한 대로 데이터가 업데이트 또는 삭제되는지 확인
* 삭제된 상품이 조회되지 않는지 테스트 필요
* 잘못된 의류 ID로 요청 시 ClothesSizeNotFoundException이 올바르게 발생하는지 확인

feat: 상품 관리 기능 추가(update, delete)

---

src/main/java/com/example/demo/clothes/dto/response/GetClothesDetailResponse.java
src/main/java/com/example/demo/clothes/dto/response/GetClothesResponse.java
src/main/java/com/example/demo/clothes/service/ClothesService.java

* 의류 정보 조회 시 이미지(상품, 상품 설명) url을 수정하였습니다.
* 이미지 url을 s3 url로 수정하였습니다.
* response의 코드 형식을 builder로 통일하였습니다.
* 없습니다.

fix: 이미지 url 생성

---

src/main/resources/application.yml

* 업로드 되는 파일의 용량이 큰 경우 413 에러를 반환하는 문제 발생 -> 용량을 10MB로 늘려 해당 문제 해결
*
*
*

fix: file upload size limit change

---

src/main/java/com/example/demo/cart/controller/CartController.java
src/main/java/com/example/demo/cart/controller/CartControllerImpl.java
src/main/java/com/example/demo/cart/dto/request/AddToCartItemRequest.java
src/main/java/com/example/demo/cart/dto/request/UpdateCartItemRequest.java
src/main/java/com/example/demo/cart/dto/response/GetCartResponse.java
src/main/java/com/example/demo/cart/entity/Cart.java
src/main/java/com/example/demo/cart/exception/CartErrorCode.java
src/main/java/com/example/demo/cart/exception/CartNotFoundException.java
src/main/java/com/example/demo/cart/repository/CartRepository.java
src/main/java/com/example/demo/cart/service/CartService.java
src/main/java/com/example/demo/cart/service/application/CartApplicationService.java
src/main/java/com/example/demo/clothes/entity/ClothesSize.java
src/main/java/com/example/demo/clothes/service/ClothesSizeService.java
src/main/java/com/example/demo/common/security/AccessPath.java
src/main/java/com/example/demo/exception/ClothesErrorCode.java
src/main/java/com/example/demo/exception/ClothesInsufficientStockException.java
src/main/resources/application.yml
src/test/resources/application.yml

release: 0.1.174

---

src/main/java/com/example/demo/clothes/dto/request/CreateClothesRequest.java
src/main/java/com/example/demo/clothes/dto/request/UpdateClothesRequest.java
src/main/java/com/example/demo/clothes/dto/response/GetClothesDetailResponse.java
src/main/java/com/example/demo/clothes/entity/Clothes.java
src/main/java/com/example/demo/clothes/service/ClothesService.java

* 기존 Clothes 엔티티에  mtlKey 필드를 추가하고자 합니다.
* Clothes 엔티티 클래스에 mtlKey 필드가 새롭게 추가되었습니다.
* 상품 생성 및 수정 요청 로직에 mtlKey를 포함하도록 수정되었습니다.
* 상품 상세 조회 응답 로직에서 mtlKey를 포함하여 응답하도록 변경되었습니다.
* 생성, 수정 시 데이터 유효성 검증 로직이 일부 보강되었습니다.
* 관련된 DTO와 매퍼 클래스에도 mtlKey 필드를 반영했습니다.
* 없습니다
close #90 #91

mtl 파일을 저장하기 위해 필드 추가

---

src/main/java/com/example/demo/clothes/dto/request/CreateClothesRequest.java
src/main/java/com/example/demo/clothes/dto/request/UpdateClothesRequest.java
src/main/java/com/example/demo/clothes/dto/response/GetClothesDetailResponse.java
src/main/java/com/example/demo/clothes/entity/Clothes.java
src/main/java/com/example/demo/clothes/service/ClothesService.java

-Clothes 엔티티 클래스에 mtlKey 필드 추가
-상품 생성, 수정 request, 로직에 mtlKey 필드 추가
-상품 상세 조회 response, 로직에 mtlKey 추가
* 
*
*
*

release: 0.1.175

---

src/main/java/com/example/demo/common/util/FileExtensionUtils.java

FileExtensionUtils에 .mtl 파일 형식도 지원하도록 추가하였습니다
* 
*
*
*
close #99

release: 0.1.211

---

src/main/java/com/example/demo/cart/dto/response/GetCartResponse.java
src/main/java/com/example/demo/cart/service/application/CartApplicationService.java
src/main/java/com/example/demo/controller/CartController.java
src/main/java/com/example/demo/controller/CartControllerImpl.java
src/main/java/com/example/demo/controller/OrderController.java
src/main/java/com/example/demo/controller/OrderControllerImpl.java
src/main/java/com/example/demo/order/dto/response/GetOrderResponse.java
src/main/java/com/example/demo/order/service/application/OrderApplicationService.java

* 장바구니에 같은 옷 다른 사이즈 추가시, url이 반복적으로 붙는 오류 수정
* 우선 controller 패키지를 모아두도록 수정
*
*
*
- closed : #104

bug: Clothes 불변 객체 미사용으로 인한 이미지 주소 오류

---

src/main/java/com/example/demo/clothes/dto/request/UpdateClothesRequest.java
src/main/java/com/example/demo/clothes/service/ClothesService.java

* 상품 수정 시 `required` 속성이 적용되어 선택적으로 입력되어야 하는 필드가 필수로 처리되는 문제를 수정하고자 합니다.
* 원인인 스키마 name을 수정하였고, 상품 수정 request body에서 `example` 값을 제거하여 Swagger에서 수정하지 않는 값이 포함되지 않도록 변경했습니다.
* 없습니다.
* Swagger를 통해 선택적 필드가 정상적으로 `required` 속성을 가지지 않는지 확인이 필요합니다.
* 수정된 request body를 이용한 API 호출 시 수정하지 않는 값이 포함되지 않는지 검증이 필요합니다.

fix: 상품 수정 request body 설정 수정

---

src/main/java/com/example/demo/cart/dto/response/GetCartResponse.java
src/main/java/com/example/demo/cart/service/application/CartApplicationService.java
src/main/java/com/example/demo/clothes/dto/request/UpdateClothesRequest.java
src/main/java/com/example/demo/clothes/service/ClothesService.java
src/main/java/com/example/demo/controller/CartController.java
src/main/java/com/example/demo/controller/CartControllerImpl.java
src/main/java/com/example/demo/controller/OrderController.java
src/main/java/com/example/demo/controller/OrderControllerImpl.java
src/main/java/com/example/demo/order/dto/response/GetOrderResponse.java
src/main/java/com/example/demo/order/service/application/OrderApplicationService.java

release: 0.1.22

---

src/main/java/com/example/demo/admin/dto/request/AdminUpdateOrderRequest.java
src/main/java/com/example/demo/admin/dto/response/AdminGetOrderDetailResponse.java
src/main/java/com/example/demo/admin/dto/response/AdminGetOrderResponse.java
src/main/java/com/example/demo/admin/service/application/AdminOrderApplicationService.java
src/main/java/com/example/demo/common/security/AccessPath.java
src/main/java/com/example/demo/controller/AdminController.java
src/main/java/com/example/demo/controller/AdminControllerImpl.java
src/main/java/com/example/demo/controller/CustomerController.java
src/main/java/com/example/demo/customer/dto/response/GetAddressResponse.java
src/main/java/com/example/demo/order/entity/Order.java
src/main/java/com/example/demo/order/repository/OrderRepository.java
src/main/java/com/example/demo/order/service/OrderService.java

커밋 히스토리를 보고 PR 내용을 작성해드리겠습니다.
* 관리자가 주문을 관리할 수 있는 Admin Order API가 필요한 상황
* 주문 상태 변경 및 주문 목록 조회 기능 구현 필요
* 페이지네이션을 통한 효율적인 주문 데이터 관리 필요
* Admin Order API 구현
- 주문 목록 조회 기능 추가
- 주문 상태 업데이트 기능 구현
* Admin Controller와 DTO 구조 설계 및 구현
* 페이지네이션 기능 통합
* Admin Controller DTO 기본 구조 설계
* 페이지네이션 관련 코드 리팩토링
* develop 브랜치와의 병합 작업 수행

feat: 어드민 주문 API 구현

---

src/main/java/com/example/demo/common/security/AccessPath.java
src/main/java/com/example/demo/order/dto/request/AddToOrderItemRequest.java
src/main/java/com/example/demo/order/dto/response/GetOrderDetailResponse.java
src/main/java/com/example/demo/order/service/application/OrderApplicationService.java

fix: AddressId -> addressId로 수정

---

src/main/java/com/example/demo/admin/dto/request/AdminUpdateOrderRequest.java
src/main/java/com/example/demo/admin/dto/response/AdminGetOrderDetailResponse.java
src/main/java/com/example/demo/admin/dto/response/AdminGetOrderResponse.java
src/main/java/com/example/demo/admin/service/application/AdminOrderApplicationService.java
src/main/java/com/example/demo/common/security/AccessPath.java
src/main/java/com/example/demo/controller/AdminController.java
src/main/java/com/example/demo/controller/AdminControllerImpl.java
src/main/java/com/example/demo/customer/dto/response/GetAddressResponse.java
src/main/java/com/example/demo/order/dto/request/AddToOrderItemRequest.java
src/main/java/com/example/demo/order/dto/response/GetOrderDetailResponse.java
src/main/java/com/example/demo/order/entity/Order.java
src/main/java/com/example/demo/order/repository/OrderRepository.java
src/main/java/com/example/demo/order/service/OrderService.java
src/main/java/com/example/demo/order/service/application/OrderApplicationService.java

release: v0.1.24

---

src/main/java/com/example/demo/cart/service/application/CartApplicationService.java
src/main/java/com/example/demo/clothes/dto/request/CreateClothesRequest.java
src/main/java/com/example/demo/clothes/dto/request/UpdateClothesRequest.java
src/main/java/com/example/demo/clothes/dto/response/GetClothesDetailResponse.java
src/main/java/com/example/demo/clothes/entity/Clothes.java
src/main/java/com/example/demo/clothes/service/ClothesService.java
src/main/java/com/example/demo/controller/AdminController.java
src/main/java/com/example/demo/controller/CustomerControllerImpl.java
src/main/java/com/example/demo/customer/dto/request/ProfileUpdateRequest.java
src/main/java/com/example/demo/customer/dto/request/RegisterRequest.java
src/main/java/com/example/demo/customer/dto/response/GetCustomerResponse.java
src/main/java/com/example/demo/customer/dto/response/LoginResponse.java
src/main/java/com/example/demo/customer/entity/BodyType.java
src/main/java/com/example/demo/customer/entity/Customer.java
src/main/java/com/example/demo/customer/service/CustomerService.java
src/main/java/com/example/demo/order/entity/Order.java

고객 정보를 보다 정확하게 저장하고, 로그인 시 3D 모델 파일 URL을 제공하기 위해 고객 Entity에 키, 몸무게, 체형 정보를 추가하고, 관련 요청/응답 클래스 및 서비스 로직을 수정했습니다.
* **Customer Entity**: 고객 Entity에 키(height), 몸무게(weight), 체형(bodyType) 필드를 추가하였습니다.
* **RegisterRequest, ProfileUpdateRequest**: 회원가입 및 프로필 업데이트 요청 시 키, 몸무게, 체형 정보를 포함하도록 변경하였습니다.
* **GetCustomerResponse, LoginResponse**: 응답 DTO에 키, 몸무게, 체형 정보가 추가되었으며, 로그인 시 객체 파일의 Presigned URL을 반환합니다.
* **CustomerService**: 로그인 시 고객의 성별과 체형을 기준으로 객체 URL을 생성하여 응답에 포함했습니다.
* Customer 클래스의 빌더 메서드와 업데이트 메서드가 추가된 필드에 맞추어 수정되었습니다.
* ProfileUpdateRequest에 사용되지 않는 `@NotBlank` 임포트 경고를 해결했습니다.
* Presigned URL 생성 로직에서 빈 문자열 결합 이슈를 해결했습니다.
* 회원가입 및 로그인 요청 시 추가된 키, 몸무게, 체형 정보가 올바르게 저장되고, 응답으로 해당 정보가 정상적으로 반환되는지 테스트해야 합니다.
* Presigned URL이 유효한지 확인하고, URL을 통해 올바른 객체 파일이 다운로드되는지 검증해야 합니다.
* …

회원가입시 키 몸무게 오브젝트 링크 설정
